### ISSUE TITLE
Typo in translation

### ISSUE THREAD

**Issue by code4humanity** [processing/p5.js-web-editor#1948]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

In translations.json for pt-BR there's a typo in [line 86](https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/pt-BR/translations.json#L86) where is written Enrar instead of Entrar

**Comment by code4humanity** [comment]
@catarak, can I fix it?

**Comment by catarak** [comment]
> @catarak, can I fix it?

Yes, go ahead!

**Comment by code4humanity** [comment]
@catarak, I have fixed the typo and found some other ones, which I have already fixed too. Would you mind if I opened another issue to review the translation? There are some of them which I think we could improve.

**Comment by catarak** [comment]
> Would you mind if I opened another issue to review the translation? There are some of them which I think we could improve.

Please do! I think it's important for the translations to evolve and to have a lot of different perspectives.

**Comment by AjeetSingh2016** [comment]
@catarak I think this issue is not resolved yet, can I go through it?
![issue](https://user-images.githubusercontent.com/80536741/139722556-102f7a31-1d78-4099-9b55-fb63927fca42.png)

**Comment by code4humanity** [comment]
@AjeetSingh2016, that's because the PR wasn't completed yet, but that was changed.
