### ISSUE TITLE
Saved sketch displays random sketch name on reload

### ISSUE THREAD

**Issue by mkmori** [processing/p5.js-web-editor#2526]
### p5.js version

Web Editor 2.8.0

### What is your operating system?

iOS

### Web browser and version

Google Chrome (118.0.5993.92 on iOS 16.6.1)

### Actual Behavior

After logging in and opening a named sketch, on each reload, the sketch name displays a randomly generated name.

Afaict, this is only a display issue, and the saved names are not actually changed. (But not sure what happens on re-save...?)

Incidentally, in Chrome (118.0.5993.89) for Windows, the random name is briefly displayed on reload, before being replaced by the saved named again.

### Expected Behavior

The displayed saved name should not change on reload.

~~Personally, I would propose the fun but sometimes troublesome random sketch name generator be replaced by a more predictable, straightforward default naming algorithm, like that used in the Java IDE. I'll create a GitHub issue for community consideration and discussion.~~

~~Discourse topic for opinion gathering:~~
~~(https://discourse.processing.org/t/proposal-for-web-editor-replace-random-sketch-name-generator/43023)~~

Separate issue proposing replacement of random name generator:
(https://github.com/processing/p5.js-web-editor/issues/2528)

### Steps:
1. Log in and open a saved sketch.
2. Reload.
3. Observe sketch name after reload.

**Comment by lindapaiste** [comment]
> Incidentally, in Chrome (118.0.5993.89) for Windows, the random name is briefly displayed on reload, before being replaced by the saved named again

This is something that I have noticed and it has to do with how we are setting the initial states in Redux.  I think I’ve also seen it show the new project code in the editor while it’s fetching the actual project code.  We can make some improvements here.

**Comment by Akhilbisht798** [comment]
Hey can I work on this issue.
I think this issue @mkmori has talked about 2 separate things
1. Displayed name changed after reload.
2. Replacing random name with more predictable naming pattern.

I think I can work on the reloading problem.

**Comment by lindapaiste** [comment]
The bug where the name is incorrect is only in the mobile version of the header, FYI.

@Akhilbisht798 I think the source of the bug is the `EditableInput` and that it can be fixed with a `useEffect` that calls `setCurrentValue` when the `value` prop changes.

**Comment by Akhilbisht798** [comment]
@lindapaiste ya think so that `EditableInput` is where I can find something related to this.
Hey, I will try your solution.

**Comment by Akhilbisht798** [comment]
@lindapaiste, i have tried your solution and it is working great. Enough though component is still getting first `value` as random but this is handling it pretty good.

**Comment by mkmori** [comment]
I created a separate "replace random name generator" issue (https://github.com/processing/p5.js-web-editor/issues/2528) so this one is fully resolved by the display issue fix.

Thanks, @Akhilbisht798 , @lindapaiste!

**Comment by lindapaiste** [comment]
I have approved and merged @Akhilbisht798's PR #2548 which fixes the major bug where the sketch shows the wrong name indefinitely.

We still have the issue where it shows a placeholder name and code while the sketch is loading.  This is less important and also harder to fix.  We can create a separate issue for that.
