### ISSUE TITLE
When resizing the window uploaded `image` gets greyed out and shifts to bottom 

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2603]
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

When resizing the window uploaded `image` gets greyed out and shifts to bottom 
<img width="748" alt="image-responsive" src="https://github.com/processing/p5.js-web-editor/assets/47579287/3aadf8b0-c6f6-4b9a-a95b-f5d18333ceff">

### Expected Behavior

When resizing the window uploaded `image` should not get greyed out and should remain at its initial position. Perhaps it's not fully responsive at some extent, also the width of the side bar is unnecessarily large and i think this is the root cause

### Steps:
1. Open the editor web app
2. Click on sidebar expand icon
3. Click on "+"
4. Click on upload file
5. Upload an image
6. Resize the widow
7. Verify the image gets greyed out and shifts to bottom

**Comment by lindapaiste** [comment]
Good catch.  It is not just while resizing.  Previewing an image is messed up when in the mobile size range.  I'm seeing the image show up below the code editor.  We should be just showing the image (`AssetPreview`) and not showing the editor at all when you are viewing a media file.  It is hidden via CSS when on desktop but not on mobile.

https://github.com/processing/p5.js-web-editor/blob/411ff89406099d072b5b04c7dec0d07be9941160/client/modules/IDE/components/Editor/index.jsx#L504-L508

**Comment by Akhilbisht798** [comment]
Hey, i am not sure about the greyed part of this issue but i can confirm that the image is shifting toward the bottom of the screen.

**Comment by Akhilbisht798** [comment]
```js
                <EditorHolder
                  ref={(element) => {
                    this.codemirrorContainer = element;
                  }}
                  className={editorHolderClass}
                />
```
I think this will solve the problem, but I am not able to test it because It requires a s3 bucket to upload a file.
And I don't have one so

**Comment by aditya123473892** [comment]
@lindapaiste  can i be assigned with issue if no one is working on it

**Comment by aditya123473892** [comment]
i was trying to upload image on the local host but i am not able to upload images should  i create a new issue about it as its working fine on normal p5.js web site

**Comment by Harshit-7373** [comment]
@raclim This issue is solved now you can close this issue.

<img width="1505" alt="Image" src="https://github.com/user-attachments/assets/c25b924d-575f-401f-a13f-5b69712931dc" />

In the uploaded image , You can see that the issue no longer persists.

**Comment by raclim** [comment]
@Harshit-7373 I just tried it out and this issue is still persisting for me. I think you have to ensure that you're previewing the image by clicking on the image file and viewing it in the editor. I'll post some screenshots of what I'm seeing below. 

**SVG Uploaded to the Editor**: 
<img width="1361" alt="Image" src="https://github.com/user-attachments/assets/7692517b-6406-48fd-b144-cf49c8d7857d" />

**SVG Preview Disappearing When Resizing Browser Window**:
<img width="725" alt="Image" src="https://github.com/user-attachments/assets/b0cf7698-191d-4ee6-9176-d20b286a2b10" />

**SVG Preview in Mobile View**:
<img width="498" alt="Image" src="https://github.com/user-attachments/assets/b2b92584-9f9f-4a6f-bcc5-7c7ee97102fb" />

**Comment by Harshit-7373** [comment]
@raclim I have found the issue . Yes the issue still persists. I will look into it and will surely create a PR that will solve this issue.
