### ISSUE TITLE
Not able to scroll the Privacy policy, Terms of use, and Code of conduct pages in mobile view

### ISSUE THREAD

**Issue by haarsh157** [processing/p5.js-web-editor#2905]
### p5.js version

2.10.2

### What is your operating system?

None

### Actual Behavior

Cannot scroll the Privacy policy, Terms of use, and Code of conduct pages in mobile view

https://github.com/processing/p5.js-web-editor/assets/115213858/baf4d282-b183-4ad6-8b60-dab59b0a15e4

### Expected Behavior

The Privacy Policy, Terms of Use, and Code of Conduct pages should be scrolled to the end.

### Steps:
1. Open mobile view.
2. Go to about section then to Privacy Policy or Terms of Use or Code of Conduct page.
3. Try to scroll through the page.

**Comment by haarsh157** [comment]
Hi @lindapaiste , I would like to work on this issue

**Comment by lindapaiste** [comment]
> Hi @lindapaiste , I would like to work on this issue

Sure, we definitely want to fix this!

**Comment by lindapaiste** [comment]
There's probably a few valid ways to fix this, with differences in what content is fixed to the top.  One way would be in the `PolicyContainer`.  We would add an `overflow: auto` and remove the `min-height: 100vh;` when in the mobile view.

**Comment by raclim** [comment]
I'm going to reopen this again since it wasn't fully resolved, which is explained in this comment: https://github.com/processing/p5.js-web-editor/pull/2930#issuecomment-2018615999!
