### ISSUE TITLE
Nav item first toggles back then openes

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#899]
Click on any navbar say 'Help & Feedback' , now click on Edit ,it won't open.
This is happening because the dropdown is set to 'none' first time and then changes to edit.
Will send a PR Soon

**Comment by catarak** [comment]
yeah, this UX is a little awkward—you have to click "Edit" twice for it to open.

**Comment by siddhant1** [comment]
Investigating and working on this :)

**Comment by catarak** [comment]
i wonder if this is indirectly solved by #900?

**Comment by siddhant1** [comment]
Nope  , it's still happening . Will fix it and send a separate pr tomorrow.

**Comment by siddhant1** [comment]
I think  we can close this @catarak

**Comment by catarak** [comment]
i think this needs to be fixed for keyboard users. try the following:
1. Tab to "File"
2. Hit enter
3. Tab through the options until "Edit" is highlighted
4. Dropdown under "File" is still open.

I think one of two things should happen, either (1) the dropdown under "File" should close, or (2) the dropdown under "Edit" should open.

**Comment by shakti97** [comment]
Can I work on this or its done but not closed?

**Comment by catarak** [comment]
i just tested this, and i think it's actually been fixed. closing!
